---
- hosts: labservers
  become: yes
  tasks:
  - name: Stop httpd service
    service:
      name: httpd
      state: stopped
      enabled: false

  - name: Remove httpd package
    yum:
      name: httpd
      state: absent
