- name: Install Apache and starts the service
  hosts: labservers
  become: yes
  tasks:
  - name: Install the require package
    yum:
      name: "{{ ansible_local.custom.general.package }}"
      state: latest

  - name: Start service
    service:
      name: "{{ ansible_local.custom.general.service }}"
      state: "{{ ansible_local.custom.general.state }}"